vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        movies_poster:
            uri_prefix:         '/%app.posters.dir%'
            upload_destination: '%kernel.project_dir%/public/%app.posters.dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer