<?php

namespace App\Tests\Entity;

use App\Entity\Movie;
use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class MovieTest extends KernelTestCase
{
    protected function setUp(): void
    {
        self::bootKernel();

        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testSomething(): void
    {
        $this->assertTrue(true);
    }

    public function testMovieTitleIsRequired(): void {
        $movie = new Movie();
        $movie->setPoster("novalid.jpg");
        $container = static::getContainer();
        $validator = $container->get(ValidatorInterface::class);
        $violations = $validator->validate($movie);
        $this->assertEquals(count($violations), 2);
        $this->assertEquals("novalid.jpg", $movie->getPoster());

    }
}
